name: zSchedulers
author: Maxlego08
main: fr.maxlego08.zscheduler.SchedulerPlugin
website: https://groupez.dev
description: Scheduler plugin
folia-supported: true
version: 1.0.7
api-version: 1.13
depend:
  - PlaceholderAPI
commands: